# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f0b896a9cf0cdfda053ed058d52cba0"
name = "cartrabbit-task-app"
handle = "cartrabbit-task-app-1"
application_url = "https://makers-lived-trackbacks-feb.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-02"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://makers-lived-trackbacks-feb.trycloudflare.com/auth/callback",
  "https://makers-lived-trackbacks-feb.trycloudflare.com/auth/shopify/callback",
  "https://makers-lived-trackbacks-feb.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
